apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ci-cd"
  description: "Teste CICD"
  annotations:
    backstage.io/techdocs-ref: dir:.
    idp.mycompany.com/infrastructure-repository: "https://github.com/romagalhaes/ci-cd-infra"
    idp.mycompany.com/infrastructure-entity-ref: "component:default/ci-cd-infra"
spec:
  type: service
  owner: "group:default/guests"
  lifecycle: experimental